### ISSUE TITLE
importFiles method - minor bug

### ISSUE THREAD

**Issue by rafal-zajdel** [matthiasmullie/minify#100]
I have found out that there is a problem in method importFiles with converting paths starting with slash. For example path inside
`.ui-icon { width: 16px; height: 16px; background-image: url(/_lay/jqueryui/ui-icons_72b42d_256x240.png); }`
is converted in my system to
`/var/www/app/www/turysta/shared/_cache/_css//_lay/jqueryui/ui-icons_72b42d_256x240.png`
so there are two slashes and the image path seems to be invalid. I have not fully analyzed the code but maybe changing the line in CSS.php :: 267 to 
`$path = dirname($source).'/'.ltrim($path,'/');`
would be a good solution?

**Comment by matthiasmullie** [comment]
Hey @rafal-zajdel, thanks for submitting this issue.

I'm unable to reproduce it, though. And I also have no idea what could be causing it: when converting paths, it should:
* ignore the path if it's absolute (starts with a /)
* rtrim & ltrim both paths before combining them
So I have no idea how this can even happen here :)

Can you tell me the path of the original CSS file & the minified CSS file?

**Comment by rafal-zajdel** [comment]
Hello @matthiasmullie, thanks for the reply.

Paths starting with slash may to be ignored but are they really ignored in a way you intended? In importFiles method in foreach loop in my example $match[2] is equal to '/_lay/jqueryui/ui-icons_72b42d_256x240.png' and dirname($source) is equal to '/var/www/app/www/turysta/shared/_cache/_css' so the final value of $path is '/var/www/app/www/turysta/shared/_cache/_css//_lay/jqueryui/ui-icons_72b42d_256x240.png' (double slash). File is not imported because $this->canImportFile($path) returns false but in some systems such paths are valid (multiple slashes treated as single slash). You could do something like $match[2]=ltrim($match[2],'/'); (if you would like to check for file existence anyway) or to proceed to the next loop iteration if $match[2] starts with a slash (to save a disk check performed by is_file()).

**Comment by matthiasmullie** [comment]
Sorry for the terribly late reply!

Paths starting with a slash are ignored, because the minifier doesn't know what the document root will be. It can resolve & import files relative to a CSS file, but it can not resolve absolute files (because then it would have to start making assumptions as to what the document root could be)

But you're right that the current check could potentially be incorrect & an absolute path could be appended to dirname path & it may still yield a valid path (not too unlikely for the dirname path to coincide with the document root)
I'm preparing a fix!
