### ISSUE TITLE
JS code with slash breaks minify result

### ISSUE THREAD

**Issue by dnyrop** [matthiasmullie/minify#108]
When using strings with a slash (/) the minify regex skips anything from the slash.
This:
```
function isHtmlNamespace(node) {
            var ns;
            return typeof node.namespaceURI == UNDEF || ((ns = node.namespaceURI) === null || ns == "http://www.w3.org/1999/xhtml");
        }
```
Minifies into this:
```
function isHtmlNamespace(node){var ns;return typeof node.namespaceURI==UNDEF||((ns=node.namespaceURI)===null||ns=="http:}
```

This bug might have been introduced in this issue: https://github.com/matthiasmullie/minify/issues/56

**Comment by matthiasmullie** [comment]
Hey @dnyrop,

I tried reproducing this problem, but it seems to work fine for me (see commit 9c9c286776ce254779cf36464100ad7482f89d1e)

Can you try increasing `pcre.backtrack_limit` & `pcre.recursion_limit` (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

If the problem persists, please reopen this issue & provide the complete JS file as the problem may be caused in another part of the code, but only become visible here.
You can send me the code via http://www.mullie.eu/contact/ if you want to keep it private.

**Comment by ovidiu-ostafi** [comment]
The previous error happens when we try to minify these library in this exact order:
`
'jquery.min.js',
'bootstrap-datepicker.js',
'wysihtml-toolbar.js',
'advanced_and_extended.js'
`

However if datepicker is switched with the wysihtml editor no error is present:
`
'jquery.min.js',
'wysihtml-toolbar.js',
'bootstrap-datepicker.js',
'advanced_and_extended.js'
`

My guess is that it's the datepicker.

Full paths to libraries:

- https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
- https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js
- https://github.com/Voog/wysihtml/blob/master/dist/wysihtml-toolbar.js
- https://github.com/Voog/wysihtml/blob/master/parser_rules/advanced_and_extended.js

I am are aware that this might not be a minify library problem but rather a bad coding issue from one of these libraries, however I would like to know which character is causing the problem.

@dnyrop  line from above is from wysihtml-toolbar.js library.

**Comment by matthiasmullie** [comment]
Thanks for the additional details.

I was able to reproduce the problem with in the given order with a `pcre.backtrack_limit` of 10000.
But if you increase the `pcre.backtrack limit`, it minifies correctly. Try:

```php
ini_set( 'pcre.backtrack_limit', 100000 );
```

**Comment by ovidiu-ostafi** [comment]
We do have that set to default which means 1 million: http://php.net/manual/en/pcre.configuration.php

So lowering that that doesn't really make sense.

**Comment by matthiasmullie** [comment]
Lowering it indeed makes no sense. But 100000 seemed to work for me to minify just these 4 files correctly.
Can you try increasing it even more?

**Comment by GinoPane** [comment]
I do not know if it makes sense, but what about setting this value explicitly in `Minify` itself and then restoring it to the user's value?
