### ISSUE TITLE
Permissions error : "The file could not be opened, check if PHP has enough permissions"

### ISSUE THREAD

**Issue by WilliamVercken** [matthiasmullie/minify#12]
Hi,
Here is what I have :

```
require_once __DIR__.'/../minify/Minify.php';
require_once __DIR__.'/../minify/CSS.php';
require_once __DIR__.'/../minify/JS.php';
require_once __DIR__.'/../minify/Exception.php';
use MatthiasMullie\Minify;

$file1 = '/media/css/main.css';
$file2 = '/media/js/jquery/plugins/jquery-ui/css/jquery-ui-1.10.4.custom.min.css';
$minifier = new Minify\CSS($file1, $file2);
$minifier->minify('/media/combined.css');
```

When I try to combine $file1 and $file2, I have these errors : 

```
Fatal error: Uncaught exception 'MatthiasMullie\Minify\Exception' with message 'The file "/media/combined.css" could not be opened. Check if PHP has enough permissions.' in C:\wamp\www\ariakan.core.local.net\minify\Minify.php on line 108
```

```
MatthiasMullie\Minify\Exception: The file "/media/combined.css" could not be opened. Check if PHP has enough permissions. in C:\wamp\www\ariakan.core.local.net\minify\Minify.php on line 108
```

What should I do ?

I'm using Wamp -> PHP 5.4.16 - Apache 2.4.4
It doesn't work ether on my server. I have no error showed, but I have this in my PHP logs :

```
[07-Feb-2014 15:45:08 UTC] PHP Fatal error:  Uncaught exception 'MatthiasMullie\Minify\Exception' with message 'The file "/media/combined.css" could not be opened. Check if PHP has enough permissions.' in /srv/data/web/vhosts/core.ariakan.com/htdocs/minify/Minify.php:108
Stack trace:
#0 /srv/data/web/vhosts/core.ariakan.com/htdocs/minify/CSS.php(340): MatthiasMullie\Minify\Minify->save('/media/css/main...', '/media/combined...')
#1 /srv/data/web/vhosts/core.ariakan.com/htdocs/common/functions.php(12): MatthiasMullie\Minify\CSS->minify('/media/combined...')
#2 /srv/data/web/vhosts/core.ariakan.com/htdocs/index.php(1): include('/srv/data/web/v...')
#3 {main}
  thrown in /srv/data/web/vhosts/core.ariakan.com/htdocs/minify/Minify.php on line 108
```

Thanks a lot ! :)

**Comment by jcheymans** [comment]
The same thing is happening to me. Already chmod permissions to the folder and file. Please help!

**Comment by jlaustill** [comment]
This same thing is happening to me, and PHP has to have enough permissions because the file it is minifying was just written by PHP in the same directory.  The directory in my case is owned by www-data:www-data and that is also the PHP user.

**Comment by jayvin** [comment]
@jlaustill : Find another approach for 'PHP has enough permissions issue'
$filePath = 'PATH TO FILE';
$fileContents = file_get_contents($filePath);
$minifier = new Minify\JS($fileContents);
$minifiedContents = $minifier->minify();
$outputFilePath = 'PATH OF OUTPUT FILE';
file_put_contents($outputFilePath, $minifiedContents);

**Comment by allanrehhoff** [comment]
Had the same issue here.

Checked all parent/ancestor folders of the destination files, and all had 755 permissions.

Changed:
`$minifier->minify($destinationPath);`

To
```
$minified = $minifier->minify();
file_put_contents($destinationPath, $minified);
```

Worked perfectly, and now after reverting that error, i'm unable to reproduce the error again.

Perhaps someone should try remove the error surpression '@' in **Minify.php:410** next time, to see what actually happens.

How about considering putting the error into the error log thought `error_log();` and `error_get_last();` instead of just surpressing the error

**Comment by masimao** [comment]
I got the same issue and i discover that the folder must be already created before write into the file. Just put this code before try to save the minified file.

    if ( ! is_dir($dirname)) {
        mkdir($dirname, 0755, true);
    }

**Comment by S-l-i-m** [comment]
Not really sure how old this is, but i was having the same issue... Now im a bit new to PHP so this may be a bad idea (though it works, if someone with more experience is against it please note why its a bad idea so we all can learn from it).

Going on allanrehhoff's suggestion i removed the '@' from fopen and had no change in the result.. so i dumped the path variable just to make sure that the path was correct.

In Minify.php (for me its line 414) at openFileForWriting($path), the path variable being passed starts with a '/' where as most other paths ive seen passed to PHP functions lack the initial slash.. 

So in the statement:
`if (($handler = @fopen($path, "w")) === false)`

simply removing the initial slash on the path variable with:
`substr($path, 1, strlen($path))`
seems to fix the issue.

Ive used fopen in exactly the same way in the past with no exceptions being thrown, so i would believe that the reason were seeing the exception is because of the path formatting, why that 'should' be an issue (or i suppose 'could' is a better word) im really not sure... but regardless this does fix the issue at least for me.

Also note: I got curious as to why the initial slash was there (moreso in reference to the example on the main page, because after all thats how its getting in the minified path).. so i tried it without the slash, and without any modification to Minify.php (except for removing the '@' on fopen), and though the minifier did work, there was some issue with my reset stylesheet not working correctly and every element had an ugly frame around it.. Now if someone wants to explore and recreate that to figure out why be my guest.. but as far as a working solution with the code posted above im having no issues from it.

Hope this helps you guys. Cheers.

**Comment by edineibauer** [comment]
The problem is that the final path has to be a file.
ex:

> $minify->minify("path/css/style.min.css");

**Comment by aliibrahimroshan** [comment]
Make sure using absolute path to the folder 

 $sourcePath = FCPATH.'assets\css\style.css';

        $fileContents = file_get_contents($sourcePath);

        $minifier = new Minify\CSS($fileContents);
        $minifiedContents = $minifier->minify();

        // we can even add another file, they'll then be
        // joined in 1 output file
        //$sourcePath2 = '/path/to/second/source/css/file.css';
        //$minifier->add($sourcePath2);

        // save minified file to disk
        $minifiedPath = FCPATH.'assets\css\minified_style.css';
        file_put_contents($minifiedPath, $minifiedContents);
        //$minifier->minify($minifiedPath);

**Comment by khrismuc** [comment]
Just for reference, I did encounter this error in Windows and it was easily resolved by removing the slash from the start of the path.
I.e. `$minifier->minify($path);` didn't work because $path was `/css/theme.min.css`, and changing it to `css/$match[1].min.css` was what fixed it for me.
