### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Donny5300** [matthiasmullie/minify#125]
Great package, i love it 👍 

Only one thing i miss: why dont you return `$this` when using the public function `add()`? It would be easier to chain

**Comment by PeeHaa** [comment]
What do you gain by chaining here?

**Comment by eko3alpha** [comment]
Chaning is more or less syntatic sugar.  You don't really gain much except maybe saving a few keystrokes.  For example if you had a few css  files you wanted to add instead of doing:

````
$minifier->add('/css/style1.css');
$minifier->add('/css/style2.css');
$minifier->add('/css/style3.css');
````

you would be able to do this with chaining

````
$minifier->add('/css/style1.css')
         ->add('/css/style2.css')
         ->add('/css/style3.css');
````

Wouldn't hurt to have it.  Many libraries return $this when setting config values.

**Comment by matthiasmullie** [comment]
I see little benefit, but then again there's no harm in adding it.
