### ISSUE TITLE
Minification breaks code

### ISSUE THREAD

**Issue by oniramarf** [matthiasmullie/minify#136]
Hi,

I have used for a while this fantastic application to minify javascript code using php and I have found a strange issue. For istance, considering the following piece of code

`if ('x'+a in foo && 'y'+b[a].z in bar)`

was minified into this

`if('x'+a in foo&&'y'+b[a].zin bar)`

Could anyone help me solve this issue?

Edit: I am using the last version (1.3.35)

**Comment by matthiasmullie** [comment]
Hey @oniramarf 

I can no longer reproduce this. I believe this was also fixed with 9e0dfaf1b11c0160a29daf74793d7c028e1df0ce. Can you try again with minify's current master version?

**Comment by kualojo** [comment]
Hi,

I was experiencing the same problem. Your fix has resolved all such instances bar one.

`XPRSHelper.isManagable = function(presetId){
	if (presetId in XPRSHelper.presetTypes){
		return  (XPRSHelper.presetTypes[presetId]["GROUP"] in {"FEATURES":true,"SLIDESHOWS":true,"GALLERIES":true});
	}
	return false;
};`

becomes:

`XPRSHelper.isManagable=function(presetId){if(presetId in XPRSHelper.presetTypes){return(XPRSHelper.presetTypes[presetId].GROUPin{"FEATURES":!0,"SLIDESHOWS":!0,"GALLERIES":!0})}
return !1};`

Output is fixed by adding the space between 'GROUP' and 'in'.

Thanks

**Comment by matthiasmullie** [comment]
The whitespace thing should also have been fixed, with 9e0dfaf1b11c0160a29daf74793d7c028e1df0ce :)
