### ISSUE TITLE
CSS relative url() paths converted to mess

### ISSUE THREAD

**Issue by assarte** [matthiasmullie/minify#153]
Hi,

I should comment out line 458 at CSS.php (`$url = $converter->convert($url);`) because of it converts all of my "../somethingfont.woff" into "../../../../../somethingfont.woff" (no matter of what file extension used), pointing it up to document root instead of just the parent directory. I'm unsure if this is in the picture, these URLs contains querystrings appended to them (in most of the cases).

Used version is: 1.3.42
Installed using composer.
Platform: PHP 5.4, Linux Mint, 32bit.

Could I suggest if this feature can be enabled/disabled in future versions a way or two, please? It would be better than an instant solution like the one I used, also left a little bit of control in the hands, I mean there may be a reason why someone chosen using a form of URL instead of another.

Though, your lib is really awesome, thank you for your work!

**Comment by fernandoval** [comment]
I have the same issue.

When the component Convert is used to fix relative path the result is an inaccessible URL that result in 403 or 404 error to the client.

In my case, the path is converted to '../../../../system/assets/fonts/', but the files are not under system subdir and this path is not visible to the browser because this is relative to the source file and not to the path of the minified file.

I changed the CSS.php myself and added an property called $fixRelativePath with true value by default and a method called setFixRelativePath($value) to change it value. Finally I put the line where the URL is converted inside an if condition.

How this is not an exclusive issue to me, I did fork the project and opened a pull request.

If you want, you can try my chages until Matthias Mullie accept (or not) my pull request.

**Comment by matthiasmullie** [comment]
Up until now, I still have not seen a specific example where the path conversion behaves incorrectly (feature-wise, beyond what can be bugfixed)

Until I'm able to replicate problems or understand specific issues with it, I'm not keen to add a public method for disabling it.

However, I just submitted a commit that will make it a lot easier to override the path converter.
You can now subclass the minifier & make it work with a different converter, like this:

```php
class NoConverterCSS extends MatthiasMullie\Minify\CSS
{
    protected function getPathConverter($source, $target)
    {
        return new MatthiasMullie\PathConverter\NoConverter();
    }
}
```

A lot more maintainable than having to edit files in this vendor :)

**Comment by fernandoval** [comment]
It is simple.

Create an application with this structure:

- application/http_doc/assets/css/.gitignore
- application/http_doc/assets/img/background.jpg
- application/http_doc/index.html
- application/src/assets/css/style.css
- application/app/main.php
- application/vendor/.gitignore

Configure Apache or Nginx to point the doc root directory to _"application/http_doc/"_.

**application/http_doc/index.html**
```
<!DOCTYPE html>
<html>
  <head>
    <title>test</title>
    <link rel="stylesheet" href="/assets/css/style.css">
  </head>
  <body>Hello world!</body>
</html>
```

**application/src/assets/css/style.css**
```
body {
  background_image: '../img/background.jpg';
}
```

In **_'application/http_doc/index.php'_** use your component to minify _'application/src/assets/css/style.css'_ to _'application/http_doc/assets/css/style.css'_.

The minified file _'application/http_doc/assets/css/style.css'_ file will be like this:
```
body{background_image: 'application/src/assets/img/background.jpg';}
```

Then in spect you will see a 404 error to the JPeg file.

However you can implement a better solution than my uggly code.

**Comment by matthiasmullie** [comment]
Thanks for the detailed response! I'll try to look at this in more detail tomorrow. Meanwhile, re-opening this.

**Comment by matthiasmullie** [comment]
I see what's happening there. The source CSS file references a non-existing file (or well, it does not exist relative to the source CSS file)

The path converter is to make sure that assets can be referenced correctly in the source file, and make sure the path is adjusted accordingly when the destination of the CSS file is different.

There already is a way to bypass the path conversion: by not working with paths to files.
If you feed the minifier the CSS content (instead of the path to the CSS file), or don't write the minified result to file, it won't fix any paths:

```php
$content = file_get_contents($source);
$minifier = new MatthiasMullie\Minify\CSS($content);
$minified = $minifier->minify();
file_put_contents($target, $minified);
```

I'm unsure what to do here. Since:
* the source CSS is "invalid" (the relative path is incorrect relative to the source CSS file)
* it's possible to bypass this by not working with paths, but plain content
* it's now also possible to subclass the minifier & provide a different (or no) converter

I'm mostly tempted not to fix this any further at this point.
