### ISSUE TITLE
Option to "Set Root Dir"

### ISSUE THREAD

**Issue by thebeline** [matthiasmullie/minify#168]
For instance, if I am running this as part of a caching system, I may pass it a number of CSS or JS files in the format of:

```
/css/file.css
```

Where `/` is not system root, but web-root, further, any `@include` statements in there would be relative to the file, as well as web-root (perhaps an options to allow/dissallow importing files from below web-root as well).

The system could first see if the path as an absolute path exists, if not, prepend web-root.  If the file still does not exist, fail.  If it does exist, depending on whether or not we allow importing below web-root, check to see if the path contains web-root and pass/fail depending.

It would also be helpful if I could `add()` compiled LESS code, and set it's relative directory.  I believe I can do make the mod to allow that easily enough, but the importing of paths that contain `/absolute/web/path.(css|img)` I believe would still fail.

Thoughts?

**Comment by matthiasmullie** [comment]
matthiasmullie/path-converter recently had [a new release where a root path could be configured](https://github.com/matthiasmullie/path-converter/commit/5e4b121c8b9f97c80835c1d878b0812ba1d607c9).

It would be possibly to update Minify to allow setting a different root path.
That said, can you provide a concrete example of how/why you would use or need this?

Minify currently expects to receive the full (filesystem) path to the files it should minify, not the relative (web-root) path. We could make it possible to configure a different root path, but one might as well prepend that root path to the file's location in the first place - right?
And once it has the full path to the root files, I believe it can figure out all includes from there, since it knows the full path to the root file?

I'm going to close this ticket since I'm unsure this is needed, but please feel free to reopen with more details, as I may be overlooking perfectly valid use cases!
