### ISSUE TITLE
Breaking jQuery minified code

### ISSUE THREAD

**Issue by masimao** [matthiasmullie/minify#173]
minify is changing a code from jQuery 2.2.4 from:
`    {},h++`
To:
`    ,h++`
This is breaking the code,  please review this issue.

**Comment by matthiasmullie** [comment]
I assume the file you're trying to minify is https://code.jquery.com/jquery-2.2.4.min.js?

I tried minifying that file and it seems to have worked just fine (see commit da0a6b126142f87eec0e27039890bb37c5922957).
Can you try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.
Also make sure you're using the latest minifier code!

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)

**Comment by peixotorms** [comment]
I think... it's not a matter of increasing pcre limits, it's about the minification stripping off the `{}` part.
On jQuery, this should be preserved.

**Comment by matthiasmullie** [comment]
This may not be a PCRE limits issue, but I couldn't reproduce it on my machine, not on Travis CI.

PCRE limits are likely to be the cause because strings, comments & regular expressions need to be extracted from the source code: they can contain anything and could confuse the rest of the minifier. With long source files & complex regexes to take them out, PCRE limits could be hit, causing this extraction to be performed inaccurately. As a result, the rest of the minification could be drastically incorrect.
Given a snippet of code doesn't minify correctly, but works for me, it's often the case that something, somewhere earlier in the source code was interpreted incorrectly & propagated elsewhere throughout the code. That could be an error in the minifier, or it could be a PCRE limits issues. In this case, I had the entire source file (jQuery 2.2.4) and it minified just fine for me, so PCRE limits are a very likely culprit.

Another possibility for this particular issue could've been the use of the CSS minifier instead of the JS minifier, where empty blocks are in fact being removed.

There is no "feature" in the JS minifier that strips empty `{}`.
