### ISSUE TITLE
Failing to minify specific JS code containing comment

### ISSUE THREAD

**Issue by Committing** [matthiasmullie/minify#190]
Hi, I'm getting a js error when minifying a specific line of JS that comes from a theme file called Divi.

```
function fullwidth_portfolio_carousel_slide( $arrow ) {
                    var $the_portfolio = $arrow.parents('.et_pb_fullwidth_portfolio'),
                        $portfolio_items = $the_portfolio.find('.et_pb_portfolio_items'),
                        $the_portfolio_items = $portfolio_items.find('.et_pb_portfolio_item'),
                        $active_carousel_group = $portfolio_items.find('.et_pb_carousel_group.active'),
                        slide_duration = 700,
                        items = $portfolio_items.data('items'),
                        columns = $portfolio_items.data('portfolio-columns'),
                        item_width = $active_carousel_group.innerWidth() / columns, //$active_carousel_group.children().first().innerWidth(),
                        original_item_width = ( 100 / columns ) + '%';

                    if ( 'undefined' == typeof items ) {
                        return;
                    }

                    if ( $the_portfolio.data('carouseling') ) {
                        return;
                    }

                    $the_portfolio.data('carouseling', true);

                    $active_carousel_group.children().each(function(){
                        $(this).css({'width': $(this).innerWidth() + 1, 'position':'absolute', 'left': ( $(this).innerWidth() * ( $(this).data('position') - 1 ) ) });
                    });
...
```

The part that fails:

`item_width = $active_carousel_group.innerWidth() / columns, //$active_carousel_group.children().first().innerWidth(),`

**Image of part that fails:**
![failing part](https://i.gyazo.com/d2dc306ab505b8fed46e4e02caa2ec7f.png)

**Seems to convert it to this:**
![failing part](https://i.gyazo.com/37da3edac87159eb2d04c45a0d02c146.png)
![failing part](https://i.gyazo.com/57bf164f3e51e3586efcc58e48962118.png)
![failing part](https://i.gyazo.com/dfed5759e62e3be4672d92cc321387d8.png)

**Here is the full file I am trying to minify:**
https://gist.github.com/Committing/99d27fbfc9786fbd0ae4f80da1468035
Line 1426 fails to minify correctly

Thank you - do shout if you need any extra info!

**Comment by matthiasmullie** [comment]
Hey @Committing - thanks for the report!

I added your example code to the test suite (see commit 7bb172c8fc850bed732541134325d3869ea11e5d), but I am not able to reproduce the issue - both on my own machine, or on Travis CI.
I also tried minifying the entire code in https://gist.github.com/Committing/99d27fbfc9786fbd0ae4f80da1468035, but I didn't get the error you were getting (I did get `Uncaught ReferenceError: et_pb_custom is not defined`, but that was in the original code already - possibly because I'm missing other related scripts to get this one to run)

Any chance you were using an older version of the minifier? Can you try updating to latest master and see if the problem still occurs?

If it still fails, try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)
