### ISSUE TITLE
Minify stop working in >1.3.46 for JS

### ISSUE THREAD

**Issue by sergiq** [matthiasmullie/minify#204]
First of all sorry for my poor english.

Today I just updated the package from 1.3.46 to 1.3.52 and the JS minification stop working breaking the JS execution.

Code example:
`data = data.replace(this.video.reUrlYoutube, iframeStart + '//www.youtube.com/embed/$1' + iframeEnd);`

If you change the simple quote to double quotes works properly again.

**Comment by matthiasmullie** [comment]
Hey @sergiq 

I'm not able to reproduce the issue with your code example: it seems to minify just fine for me.
Can you paste your entire code (or send it [in private](http://www.mullie.eu/contact/) if you don't want your source code visible here) - I assume minifier gets confused somewhere else in the file, but probably doesn't mess up until that line.

**Comment by vlad-ilinyh** [comment]
Hey. The same issue on minifying in v1.3.52.

The reason is Backbone.Validation in my case:
https://raw.githubusercontent.com/thedersen/backbone.validation/master/dist/backbone-validation.js

The result is partially minified. Adding source.js containing `var $element = $('.spaced .selector');` produces `var $element = $('.spaced.selector')`, cut spaces in selector.

```
    new \MatthiasMullie\Minify\JS([
            'backbone-validation.js',
            'source.js', // contains "var $element = $('.spaced .selector')"
     ])->minify('source-min.js');
```

v1.1.46 work perfectly.

**Comment by matthiasmullie** [comment]
@vlad-ilinyh I just pushed a new version that seems to fix your file.
@sergiq I couldn't reproduce the issue with your limited code example. Can you test again with the latest Minify version? If the issue still occurs, please reopen another patch and include the entire file so I can reproduce & fix the issue!

**Comment by sergiq** [comment]
@matthiasmullie works properly! thanks 👍
