### ISSUE TITLE
CSS Minify does not seems to be working on Magento Admin

### ISSUE THREAD

**Issue by rajasajidmanzoor** [matthiasmullie/minify#246]
Hello

I have installed this module and enable CSS/JS minification.
Front end is working fine, but backend of website (admin ) is not working fine.

See this image, how admin looks like

![image](https://user-images.githubusercontent.com/5917783/39068883-5317534e-44f7-11e8-9f7c-b732f3878eee.png)

**Comment by uok** [comment]
Seems like CSS is missing. Open developer tools, switch to network and reload page. Look for the CSS file and HTTPS status code, e.g. 200, 404, etc. If it works, open URL of CSS file in separate tab. Check for PHP errors or similar which usually prevent or interfere with css output

**Comment by matthiasmullie** [comment]
Hey @rajasajidmanzoor 

Well, it sure looks like something's off there, but that screenshot doesn't provide enough information.
It could be an issue with this minifier, or with some plugin using it, or just incorrect CSS, the file that could not be found, and a whole lot of other issues. I'm afraid I'm not familiar with Magento or that module you're using, so I can't really help you narrow things down.
Since it appears that none of the CSS is working, I doubt it's an issue with this minifier. It looks more like an implementation issue, of misconfiguration of the assets to be included.

If you do find out there is an issue with this minifier, please feel free to reopen this ticket. Please make sure to include the original source file, and the (incorrectly) minified result, so I can see what went wrong exactly.
