### ISSUE TITLE
.class ::checked problem

### ISSUE THREAD

**Issue by ortreum** [matthiasmullie/minify#259]
Hello

this:
```
(new \MatthiasMullie\Minify\CSS())->add("
	#layout-newsletter-change .unsubscribe :checked + label .circle, #layout-newsletter-change .pause : checked + label .circle { color: white }
")->minify();
```

results in this:
```
#layout-newsletter-change .unsubscribe:checked + label .circle, #layout-newsletter-change .pause : checked + label .circle { color: white }
```

You can not remove whitespaces before `:` if it is followed by a `{`.

Thx

**Comment by ortreum** [comment]
This worked:
```
#layout-newsletter-change .pause :checked + label[for] .circle
```

And this doesn't:
```
#layout-newsletter-change .unsubscribe:checked + label .circle,
```

It might have something to do with the `,`. Please remove the whitespaces around `+` and `>` before `{` too.

**Comment by matthiasmullie** [comment]
Hey @ortreum 

When I minify the first example, I get this result:

```
#layout-newsletter-change .unsubscribe :checked + label .circle,#layout-newsletter-change .pause :checked + label .circle{color:white}
```

No whitespace before `:` gets deleted. The whitespace after it gets deleted, but a bare `:` in a selector is incorrect CSS anyway, so that's alright.

So while I'm not sure what's wrong with how `:` are treated (and as such did not change anything), I did submit a commit to remove whitespace around `+` and `>`.
