### ISSUE TITLE
Problem with minimized array notation

### ISSUE THREAD

**Issue by holtkamp** [matthiasmullie/minify#27]
(I thought I submitted this issue yesterday, but can not find it anymore)
It seems that
https://github.com/matthiasmullie/minify/commit/9c160601ad2ade1efe5499184e338b9fee46ccfa introduces a problem with some Javascript snippets, for example: http://css-tricks.com/snippets/jquery/make-jquery-contains-case-insensitive/

```
$.extend($.expr[":"], {
    icontains: function(elem, i, match, array) {
        return (elem.textContent || elem.innerText || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
    }
});
```

is minified into
```
$.extend($.expr.:,{icontains:function(elem,i,match,array){return(elem.textContent||elem.innerText||"").toLowerCase().indexOf((match[3]||"").toLowerCase())>=0}});
```

Which breaks. Is the reduction of 4 characters (['']) really worth the potential 'trouble'?

**Comment by matthiasmullie** [comment]
Thanks for reporting!
This should now be fixed with https://github.com/matthiasmullie/minify/commit/8f38d48a38481e5eefa1a7d436639cd1561c4ab0
I've pushed a new release as well: https://github.com/matthiasmullie/minify/releases/tag/1.3.13

I agree that the reduction is pretty small, and unfortunately caused breakage. Hopefully, it should now be fixed :)
