### ISSUE TITLE
Webfont issue

### ISSUE THREAD

**Issue by webbird** [matthiasmullie/minify#39]
I have a CSS file loading a Webfont like so:

    @font-face {
	font-family: 'blackcat';
	src:url('../webfont/blackcat.eot');
	src:url('../webfont/blackcat.eot?#iefix') format('embedded-opentype'),
		url('../webfont/blackcat.svg#blackcat') format('svg'),
		url('../webfont/blackcat.woff') format('woff'),
		url('../webfont/blackcat.ttf') format('truetype');
	font-weight: normal;
	font-style: normal;
    }

Problem is, after minifying the relative URLs are not valid anymore. They should be resolved like @imports.

**Comment by matthiasmullie** [comment]
Can you copy what they were minified to?

Once you've added an output file, were the paths then corrected, or were they still wrong?

**Comment by webbird** [comment]
They're just left untouched. -> src:url('../webfont/blackcat.eot');

**Comment by matthiasmullie** [comment]
I'm a little fuzzy on exactly what you did (writing minified results to a file or not), so I'm not sure what should be expected.

As I see it:

* If you didn't specify a file to write the minified result to, the paths should remain untouched (since we can't know what to convert them to)
* If a new destination is passed to minify(), the relative paths should be converted...
* ... or not, if the destination file is in the same folder the source file was in (or otherwise results in the same path)

I have just pushed some tests (https://github.com/matthiasmullie/minify/commit/5114e7f22ca97e0db10896833ed9aaeab03944f5) which confirm all 3 possibilities, although they probably would have failed before I worked on that other bug you filed :)

I'll consider this fixed - feel free to re-open should you disagree.

I'll push a new release with these fixes in a couple of days, so let me know if this didn't fix it for you!

**Comment by webbird** [comment]
I'm sorry for being unclear. I tried passing a path and the paths were left untouched. However, I will try your changes. Thank you.

**Comment by matthiasmullie** [comment]
@webbird Did the changes work as you'd expect? (with path: correctly updated paths relative to new path; without path: left them untouched)

**Comment by webbird** [comment]
I did not have the time to check this out yet. Sorry.

**Comment by matthiasmullie** [comment]
No problem. I'll release 1.3.19 in 2 days. Don't worry if you have no time to test by then, we can always address issues, should there be any, in later versions!
