### ISSUE TITLE
Difference in original and minified content

### ISSUE THREAD

**Issue by HarpyWar** [matthiasmullie/minify#43]
Tested with the latest minify version.

Original JSON http://pastebin.com/RwMTYurP
Minified JSON http://pastebin.com/YnFwQG4J

Search by `"Напряжение сети, В":"features"` in minified content &mdash; it's invalid value. 
Value of `"Напряжение сети, В"` must be an integer (wrapped in string). But it is minified with a value from the parent array name called `features`. Not always but in most cases in the example.

**Comment by matthiasmullie** [comment]
Thanks for the report!

During the minification, strings are first extracted from the source code (because string content can look similar to code) and replaced by a placeholder number. At the end, they're put back. In this case, the string was a number already, so the minifier got confused and took it for a placeholder value instead of the real string value.

https://github.com/matthiasmullie/minify/commit/09162620562ab5d8edabd76eb49ac04242fa369a fixes this problem. I'll push a new release (1.3.22) in a couple of minutes!
