### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by brunoais** [matthiasmullie/minify#52]
Are there any plans to add sourcemaps capability to minify?

**Comment by matthiasmullie** [comment]
Hadn't considered it yet. I'll look at the spec and start thinking how feasible it would be to implement. I'll get back to this!

**Comment by brunoais** [comment]
@matthiasmullie 
For the CSS, you can look at phpless:
https://github.com/oyejorge/less.php
It may have all the code you need to have it working for you.

Thank you for considering.

**Comment by brunoais** [comment]
Take a look here pls:
https://github.com/ravisorg/smSourcemap
It may just be what you can use directly or as a startup for the sourcemaps for the minification process.

**Comment by matthiasmullie** [comment]
Just a quick note that I haven't forgotten about this yet! I'm currently looking into some refactoring that should make it easier to add sourcemaps.

**Comment by brunoais** [comment]
Got it, thank you for the callback.

**Comment by brunoais** [comment]
Updates?
(just tell the truth. If you didn't have time, just mention it. I just want to make sure you didn't forget)

**Comment by matthiasmullie** [comment]
I've pushed some code to a new branch (https://github.com/matthiasmullie/minify/tree/refactor), but I've been pretty occupied since. It's still very much WIP, and I doubt I'll have a lot of time in the next couple of months (moving into a new house)

So progress is slow, but I still intend to get there. Some day.

**Comment by brunoais** [comment]
Do you think you can do it until May/2016?

**Comment by matthiasmullie** [comment]
May 2016 is still a little while :)

I definitely plan to have it done (or given up) a while before that.

**Comment by farrance** [comment]
Love your code, by the way, use the minifier for my js and css all the time. Any update on how this is going?

**Comment by matthiasmullie** [comment]
This is likely not happening. Not anytime soon, at least.
We can only consider this after #98 has completed, but even then this may prove hard because of some of the minifications being done (though I would have to look at sourcemaps spec to know exactly how this can be done)

This is not currently being worked on. I'm going to close this to avoid confusion.

**Comment by brunoais** [comment]
Oh... Too bad. I was looking forward to it... Oh well. Thanks for trying anyway.
