### ISSUE TITLE
removing extra lines

### ISSUE THREAD

**Issue by doreancl** [matthiasmullie/minify#53]
## Removing extra lines when try to remove commented lines in javascript

In the next code the minify delete **from** `image/*` **to** `g.replace(/\*/g, ".*")` , i think this happens when try to remove commented lines

### Original
```javascript
a.validator.addMethod("accept", function (b, c, d) {
    var e, f, g = "string" == typeof d ?
        d.replace(/\s/g, "").replace(/,/g, "|") :
        "image/*", h = this.optional(c);
    if (h)return h;
    if ("file" === a(c).attr("type") && (g = g.replace(/\*/g, ".*"), c.files && c.files.length))
        for (e = 0; e < c.files.length; e++)
            if (f = c.files[e], !f.type.match(new RegExp(".?(" + g + ")$", "i")))
                return !1;
    return !0
}
```

### Minified
```javascript
style="background-color:green">Mrs. Robinson</span>
a.validator.addMethod("accept", function (b, c, d) {
    var e, f, g = "string" == typeof d ?
        d.replace(/\s/g, "").replace(/,/g, "|") :
    "imageg, ". * "), c.files && c.files.length))
    for (e = 0; e < c.files.length; e++)
        if (f = c.files[e], !f.type.match(new RegExp(".?(" + g + ")$", "i")))
            return !1;
    return !0
}
```

**Comment by matthiasmullie** [comment]
Hi @doreancl & thanks for the bug report!

Judging from your example, it looks like you're trying to minify JavaScript inside an HTML page? (there seems to be some leftover HTML in the first line of your minified code)
The minifier doesn't recognize JS in HTML: it can only handle JavaScript-only files.

I added a test case (https://github.com/matthiasmullie/minify/commit/894928f067fcea2954d289ab3cbb58396d613dd5) for your original code example and it seems to minify just fine when it's only that bit of JavaScript.

I'll close this issue since I assume it's just because the JavaScript was inside HTML (which is not supported). If I misunderstood, feel free to reopen & clarify the issue and I'll look into it further!
