### ISSUE TITLE
Paths for import too long for filesystem

### ISSUE THREAD

**Issue by kainetsoft** [matthiasmullie/minify#63]
In the paths of imports also points were included. These have made the path too long.

So why not using realpath () for resolv the paths?

**Comment by matthiasmullie** [comment]
Hi @kainetsoft,

realpath() is not used because minifier may not be run on a machine that has the assests, but e.g. on a separate build server.
Well, path-converter attempts (https://github.com/matthiasmullie/path-converter/blob/master/src/Converter.php#L56) to realpath(), but just assumes the input is fine if realpath() fails.

I'm going to close this as the question has been answered, but feel free to reopen this issue should you experience any problem with this. In that case, can you please explain more thorough and preferable include an example of what is wrong, to help me understand the problem?
