### ISSUE TITLE
Issue Minifying D3JS

### ISSUE THREAD

**Issue by cpittman063** [matthiasmullie/minify#64]
I'm using your library (nicely done btw) to minify a bunch of js files. A copy of d3.js (http://d3js.org/) is throwing an error though.

This original code:

```javascript
    var d3_nsPrefix = {
        svg: "http://www.w3.org/2000/svg",
        xhtml: "http://www.w3.org/1999/xhtml",
        xlink: "http://www.w3.org/1999/xlink",
        xml: "http://www.w3.org/XML/1998/namespace",
        xmlns: "http://www.w3.org/2000/xmlns/"
    };
```

Is being turned into this:

```javascript
var d3_nsPrefix={svg:"http:xhtml:"http:xlink:"http:xml:"http:xmlns:"http:};
```

That code is producing an unexpected identifier error.  Any suggestions would be greatly appreciated.

**Comment by matthiasmullie** [comment]
Hi @cpittman063 

Thanks for the bug report.
I haven't been able to reproduce it, however.

I've added your example to the test suite (c7dcdc4934c6721b2b683f5d207a31b61da1ef44), but it seemed to works just fine.
I've also tried minified all of d3.js (to see if the problem is caused somewhere else in the file but only showing up here), but still didn't manage to reproduce this issue. This is what I got after minifying d3.js on www.minifier.org: http://pastebin.com/DtJbpWDy

All I can think of right now is:
Issue #58 looks similar. If you were minifying other files along with this one, the fix for #58 may also fix this problem. Can you try pulling the latest code and see if that works for you?

If it still fails for you, can you try increasing your `pcre.backtrack_limit`?
```php
ini_set('pcre.backtrack_limit', 100000);
```

I'm going to close the bug report since I'm not able to reproduce the problem. Don't worry about reopening this issue if the problem still persists.
