### ISSUE TITLE
many minified file

### ISSUE THREAD

**Issue by omicode** [matthiasmullie/minify#76]
Can i create many minified file with one instance of Minify?
Example: 
$minifier->add('file1.css');
$minifier->minify('file1.css');
//clear?
$minifier->add('file2.css');
$minifier->minify('file2.css');

**Comment by matthiasmullie** [comment]
There isn't, but not a bad idea :)
Any chance you can add it and pull request? If not, I'll try to get to it soon.

**Comment by omicode** [comment]
Мy solution method 
   /**
     * Remove a file or straight-up code.
     */
    protected function clear()
    {
			$this->data = array();
    }

and called it before return in minify() and gzip()

**Comment by matthiasmullie** [comment]
I've been thinking about implementing this for awhile, but decided I won't.

I've seen a couple of bug reports for people minifying 1 file at a time and concatenating themselves. Because the last `;` is stripped, that won't work. Adding this would just encourage doing that even more (but it's better to let minifier combine multiple files)

And for those who really do want to minify separate files, it's still easy enough to clone/construct a new Minify object.
